### ISSUE TITLE
No PlayerEnterLandEvent ?

### ISSUE THREAD

**Issue by eDexiam** [IncrediblePlugins/LandsAPI#1]
The lands API contains a PlayerLeaveLandEvent however I can't seem to find a PlayerEnterLandEvent, can one be added?

**Comment by Angeschossen** [comment]
You're looking for this: https://github.com/Angeschossen/LandsAPI/tree/master/src/main/java/me/angeschossen/lands/api/events/player

The PlayerLeaveLandEvent is /Lands leave not any movement.
