### ISSUE TITLE
Custom Currencies Per Land

### ISSUE THREAD

**Issue by MasterMetaphor** [IncrediblePlugins/LandsAPI#11]
|Allow each land to create a currency which can cost land claim power and can be exchanged for default server currency at a 1:1 exchange value| 

If possible it would be preferable if it it could hook into vault and allow other economy plugins to function through it.

Or allow a custom currency to be optionally enabled in the config.

**Comment by Angeschossen** [comment]
This has been posted in the Discord suggestion channel. moved
