### ISSUE TITLE
getAreaByLoc() gives a null as return

### ISSUE THREAD

**Issue by Luuk-VH** [IncrediblePlugins/LandsAPI#12]
We are working on a plugin. In the plugin there is a function that is checking if a player is trusted or its his claim.
the problem is we cant get the area by location it gives us a null. We also tried the method getArea(). And yes i am standing in a claim

```
final @Nullable Area area = FlyTime.landsIntegration.getAreaByLoc(player.getLocation());
System.out.println(FlyTime.landsIntegration.isClaimed(player.getLocation()));
System.out.println(area.isTrusted(player.getUniqueId()));
```
The output:
```
null
false
```

We have also followed the short  example on the github page. We dont know if this is a fault of us or that it is the api.

**Comment by Angeschossen** [comment]
Please make sure you set the provided scope in your pom.xml file. Otherwise it won't hook into Lands. You can check that by executing /lands about.
