### ISSUE TITLE
Check block placement, container access for player / location

### ISSUE THREAD

**Issue by tim-savage** [IncrediblePlugins/LandsAPI#13]
Is it possible to check if a player has build permission and chest access for a given location?

For example:
```
boolean canBuild = LandsAPI.buildAllowed(player, location)
boolean chestAccess = LandsAPI.accessAllowed(player, location)

It doesn't necessarily have to be a static method as shown, but I would need a simple and efficient way to check these two permissions for a player at a given location in order to integrate Lands plugin with my DeathChest plugin.

**Comment by Angeschossen** [comment]
Described here: https://github.com/Angeschossen/LandsAPI#implementing-lands

**Comment by tim-savage** [comment]
Could you take a look at this class and let me know if I've got this right? I could find no description of the parameters passed to the area.hasFlag methods. I'm mostly left wondering if the Material is required when using the BLOCK_PLACE flag, or if the three parameter version of the method is sufficient for this check (can player place a chest at this location?) Thanks in advance.

https://github.com/tim-savage/SavageDeathChest/blob/develop/src/main/java/com/winterhavenmc/deathchest/permissions/protectionplugins/plugins/Lands.java

**Comment by Angeschossen** [comment]
LGTM, but two issues:
https://github.com/tim-savage/SavageDeathChest/blob/8c465db5ff38e2ab03f6a6bd8d22f5ba0d519e05/src/main/java/com/winterhavenmc/deathchest/permissions/protectionplugins/plugins/Lands.java#L59

https://github.com/tim-savage/SavageDeathChest/blob/8c465db5ff38e2ab03f6a6bd8d22f5ba0d519e05/src/main/java/com/winterhavenmc/deathchest/permissions/protectionplugins/plugins/Lands.java#L84

Use me.angeschossen.lands.api.flags.Flags.BLOCK_BREAK etc.
The material is not required, but should be submitted if available. For example, during war, this would allow checking if the player is allowed to break this specific flag during war.

**Comment by tim-savage** [comment]
Thanks for the feedback. I switched away from static import of the flags, and everything appears to be in order.
