### ISSUE TITLE
Compatibility with LargeRaids

### ISSUE THREAD

**Issue by solarrabbit99** [IncrediblePlugins/LandsAPI#14]
I have a plugin that creates large raids.
The plugin triggers raids with fake players, and I noticed that Lands is also listening to `RaidsTriggerEvent`, and may occasionally cancel it. For compatibility sake, may I know of the mechanism used to decide whether the event is cancelled?
- Github: https://github.com/zhenghanlee/LargeRaids
- Spigot: https://www.spigotmc.org/resources/largeraids-1-14-x-1-18-x.95422/

**Comment by Angeschossen** [comment]
If the option "land.combat.block-raids" is enabled in the config and the player that triggers it is not allowed to attack players at the position of the raid, it will be cancelled.

**Comment by solarrabbit99** [comment]
> If the option "land.combat.block-raids" is enabled in the config and the player that triggers it is not allowed to attack players at the position of the raid, it will be cancelled.

Understood. Thank you much!
