### ISSUE TITLE
Lands Wild Event

### ISSUE THREAD

**Issue by InsideIntel** [IncrediblePlugins/LandsAPI#17]
I was just wondering if this existed, because I have a custom world and people keep dying or spawning in water.

**Comment by Angeschossen** [comment]
Just enable extensive check in the config under random teleportation section.

**Comment by InsideIntel** [comment]
It is on

**Comment by InsideIntel** [comment]
Here is the lands configs:
[Lands.zip](https://github.com/Angeschossen/LandsAPI/files/9366311/Lands.zip)
