### ISSUE TITLE
How to get Land through unloaded Location

### ISSUE THREAD

**Issue by 5522-VVII** [IncrediblePlugins/LandsAPI#19]
public String getLandName(Location loc){
	LandsIntegration landapi = new LandsIntegration(plugin);
	Land land = landapi.getLand(loc);
	if(land==null){
		return "Land is null";
	}else{
		return land.getName();
	}
}
But,when loc Chunk is in the unloaded state. the getLandName(loc) always return "Land is null";
How to get Land through unloaded Location

**Comment by Angeschossen** [comment]
In next v: getLandUnloaded
