### ISSUE TITLE
Add a method to check if a player can build

### ISSUE THREAD

**Issue by eDexiam** [IncrediblePlugins/LandsAPI#2]
Add a method to the API to check if a player can build in the area they're in, optionally similar methods could be added for interactions and others

**Comment by Angeschossen** [comment]
This already exists:
https://github.com/Angeschossen/LandsAPI/blob/5991e4db51b1852c7016e2720606c3711f5cabb0/src/main/java/me/angeschossen/lands/api/land/Area.java#L45

https://github.com/Angeschossen/LandsAPI/blob/5991e4db51b1852c7016e2720606c3711f5cabb0/src/main/java/me/angeschossen/lands/api/integration/LandsIntegrator.java#L101
