### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Matt-MX** [IncrediblePlugins/LandsAPI#24]
Little to no documentation for developers, default function names are not self explanatory, would appreciate some documentation to help understand what things do :)

**Comment by SpraxDev** [comment]
Having the same trouble - I do not know the plugin but am trying to upgrade an old integration hook that still uses v4. But it is hard to understand what the exact equivalent would be for the outdated calls.

The link to the API documentation at https://github.com/Angeschossen/LandsAPI/wiki/API-Update is outdated/dead too.

**Comment by Angeschossen** [comment]
Why is the link dead or outdated? Feel free to ask any questions.

**Comment by SpraxDev** [comment]
> Why is the link dead or outdated? Feel free to ask any questions.

I am refering to
> API Quickstart: https://github.com/Angeschossen/Lands/wiki/API
on the API-Updates page. That /API page redirects to the wiki starting page and there doesn't seem to be an alternative page linked on the right sidebar.

I was gladly able to find that RoleSettings have been moved to the Flags class.
You/The support bot on Discord also pointed out that the API-Updates page mentions LandSetting being "replaced" by Flags which I just didn't notice when searching for the Role equivalent.

---

In general, I think having some additional API documentation that also explain some fundamental concepts of the plugin would be great. I've never used the plugin and got a bit confused if Settings have been removed and at some point I was unsure if Flags might be a new cosmetic feature introduced with an update (e.g. like **country**/land/player flags).

**Comment by Matt-MX** [comment]
There is a lot of ambiguous code in the API, such as implementing your own War types.
The War interface has no documentation, which I also see is the same case with many other components of the API.
It's hard to determine what the methods should be returning and handing, some documentation to explain that would be appreciated a lot.

The wiki only covers very few things that a developer might need to do with the API. This wouldn't be such an issue if there were javadocs, but there aren't.

**Comment by Matt-MX** [comment]
@Angeschossen Hey do you mind making some java docs/notes for the [War ](https://github.com/Angeschossen/LandsAPI/blob/master/src/main/java/me.angeschossen.lands.api/war/War.java)classes, I'm in the process of making a custom war system and the variables names and methods are kinda ambigious.
Thanks :)

**Comment by Angeschossen** [comment]
https://jitpack.io/com/github/angeschossen/LandsAPI/latest/javadoc/

I'll add more documentation when I have time.
