### ISSUE TITLE
LandOwnerChangeEvent is not triggering correctly within Listeners. 

### ISSUE THREAD

**Issue by RazielMartelus96** [IncrediblePlugins/LandsAPI#25]
**Describe the bug**
The bug is with the `LandOwnerChangeEvent` class, in which the class, when added to a listener, does not seem to trigger when an owner of a claim is transfered via the `/land setowner <Player-Name>` command

**To Reproduce**
Due to the nature of this bug, it is merely reproduceable by trying to make a `Listener` class that utilises `LandOwnerChangeEvent`. The end user will see clearly that  the `/land setowner <Player-Name>` command does not trigger the  `Listener`

**Expected behavior**
The expected behaviour would be for the `LandOwnerChangeEvent` to be triggered in a `Listener`  that utilises the event, such as the `/land setowner <Player-Name>` command. 

**Additional Notes**
It is not known if the bug is effecting just the `/land setowner <Player-Name>` command , or indeed is a more general bug where `LandOwnerChangeEvent` is not being triggered by any action that causes an ownership change within a land claim.

**Comment by Angeschossen** [comment]
This should be fixed in the latest version. It wasn't triggered if the owner was changed by a server admin.

**Comment by RazielMartelus96** [comment]
Thanks for the reply. When is the latest version roughly estimated for release? Will keep an eye out. Cheers very much ^_^

**Comment by Angeschossen** [comment]
It's already out.

**Comment by RazielMartelus96** [comment]
To be clear, the current full release that is obtainable via maven is 6.28.11, released on febuary 18th. 

Are you refering to 6.30.0? If so the API itself has not been updated in terms of releases, unless I am missing something silly.

**Comment by Angeschossen** [comment]
The API itself didn't need an update, but the plugin itself.
