### ISSUE TITLE
Set user role on trust

### ISSUE THREAD

**Issue by quiquelhappy** [IncrediblePlugins/LandsAPI#26]
Hello,
I was unable to see how to trust a player into a land with an specific role.
I've been looking at the documentation for about 2-3h.

Thanks in advance

**Comment by quiquelhappy** [comment]
So far I've tried:
```java
Land land = Objects.requireNonNull(warp.getLand());
Role role = land.getDefaultArea().getRole(this.api.getBenefactorRole());
TrustedPlayer player = land.getTrustedPlayer(this.id);

land.getDefaultArea().setRole(player, role); // doesnt exist
land.getDefaultArea().setRole(role, player); // doesnt exist
role.setAffectedPlayers(); // do I need to use this? How? 
```

**Comment by quiquelhappy** [comment]
I saw your reply in the discord. I'll wait for the next update, then close this issue

**Comment by Angeschossen** [comment]
Added in next v:
https://github.com/Angeschossen/LandsAPI/commit/b6203012cb90c0f7528e54a093e43673578d74b6
