### ISSUE TITLE
Maven no artifact

### ISSUE THREAD

**Issue by seba4316** [IncrediblePlugins/LandsAPI#27]
No artifacts are present in the [jitpack repo](https://javadoc.jitpack.io/com/github/angeschossen/LandsAPI/7.8.10/), as can be seen from [this](https://javadoc.jitpack.io/com/github/angeschossen/LandsAPI/7.8.10/build.log) build log, the only file present in the directory, the build process fails, so there's nothing in the release.

**Comment by Angeschossen** [comment]
Thanks fixed: https://jitpack.io/#Angeschossen/LandsAPI/7.9.16
