### ISSUE TITLE
No areas displayed through API

### ISSUE THREAD

**Issue by seba4316** [IncrediblePlugins/LandsAPI#28]
I'm trying to fetch all of the areas in a land, under the assumption that area = chunk?

The following code returns an empty `Collection`:

```java
Collection<Area> areas = container.getAreas();
Bukkit.getConsoleSender().sendMessage("Areas: " + areas.size()); // 0
```

---

My goal is to delete chunks off of a `Land`. Say I have 5 chunks claimed, I want to delete chunk 5 and 4, but `ChunkCoordinate`s don't seem to have any way to be unclaimed themselves, so I was looking at areas for that.

**Comment by Angeschossen** [comment]
Areas are block sized sub areas inside the land. Use this in the next version: https://github.com/Angeschossen/LandsAPI/commit/384d7f8356cbca1636319bb9d846c4d8da7071bd

**Comment by seba4316** [comment]
My client is using version 7.2.3, and they said they can't upgrade due to a change that would break their server. Is there any way to do this without interfacing the API?
I know the plugin's obfuscated but I have enough knowledge on reflections to work it out

**Comment by Angeschossen** [comment]
> My client is using version 7.2.3, and they said they can't upgrade due to a change that would break their server. Is there any way to do this without interfacing the API? I know the plugin's obfuscated but I have enough knowledge on reflections to work it out

No. They'll need to update. I have no idea why it would break their server, though.

**Comment by seba4316** [comment]
I got this working for v7.2.3 through simple reflections with the following snippet:

```java
Class<?> clasz = Class.forName(land.getClass().getName());
Object unknown = clasz.getDeclaredMethod("RLHXh", boolean.class).invoke(land, false);
clasz.getDeclaredMethod("RLHXh", LandPlayer.class, DeleteReason.class, ChunkDeleteEvent.UnclaimType.class, unknown.getClass()).invoke(land, null, DeleteReason.UPKEEP, ChunkDeleteEvent.UnclaimType.DEFAULT, unknown);
```

I got the Land's implementation class, invoked an undocumented method to get a boolean value and finally invoked the unclaim chunk method with the reason that's correct for me.

Keep in mind that class names, method names, field names, method headers and their implementation can change with every 
update, so this code might need a some modifying to work.

**Comment by seba4316** [comment]
Update: the undocumented method `RLHXh(boolean)` gets a random `ChunkCoordinate`, so if you replace the code snippet above with a function that looks like the following you can unclaim a specific chunk.

```java
public function unclaimChunk(Land land, ChunkCoordinate chunkCoordinate) {
	Class<?> clasz = Class.forName(land.getClass().getName());
	clasz.getDeclaredMethod("RLHXh", LandPlayer.class, DeleteReason.class, ChunkDeleteEvent.UnclaimType.class, 	chunkCoordinate.getClass()).invoke(land, null, DeleteReason.UPKEEP, ChunkDeleteEvent.UnclaimType.DEFAULT, chunkCoordinate);
}
```

**Comment by Angeschossen** [comment]
> Update: the undocumented method `RLHXh(boolean)` gets a random `ChunkCoordinate`, so if you replace the code snippet above with a function that looks like the following you can unclaim a specific chunk.
> 
> ```java
> public function unclaimChunk(Land land, ChunkCoordinate chunkCoordinate) {
> 	Class<?> clasz = Class.forName(land.getClass().getName());
> 	clasz.getDeclaredMethod("RLHXh", LandPlayer.class, DeleteReason.class, ChunkDeleteEvent.UnclaimType.class, 	chunkCoordinate.getClass()).invoke(land, null, DeleteReason.UPKEEP, ChunkDeleteEvent.UnclaimType.DEFAULT, chunkCoordinate);
> }
> ```

That won't work for long, as the obfuscation can change.

**Comment by seba4316** [comment]
I know, but that will work until the plugin's updated to the latest version (which might not happen as, again, my client is only using one specific version). I'm checking for the API availability and switching to that if available
