### ISSUE TITLE
Feature Suggestion: RelationChangedEvent

### ISSUE THREAD

**Issue by tavaresjoshua8** [IncrediblePlugins/LandsAPI#29]
As the title says, an event to listen when a land or a nation changes their relation. Currently there is a “BroadcastEvent” but it only works when an enmity is declared.

**Comment by Angeschossen** [comment]
Will add that ASAP

**Comment by Angeschossen** [comment]
Added https://github.com/Angeschossen/LandsAPI/commit/f02704220f2defc841c24fbf5f766a9c470dc2fe
