### ISSUE TITLE
Console Error - Integration

### ISSUE THREAD

**Issue by TimGraham777** [IncrediblePlugins/LandsAPI#4]
Get the following error. Need to update plug-in integration. Whatever that means. Running latest release on 1.17.1 Paper. 

13.07 12:35:13 [Server] WARN java.lang.NoClassDefFoundError: com/boydti/fawe/regions/FaweMaskManager
13.07 12:35:13 [Server] WARN at me.angeschossen.lands.integration.Ftlnw.Ftlnw(?:30)
13.07 12:35:13 [Server] WARN at me.angeschossen.lands.Lands.Ftlnw(?:371)

**Comment by Angeschossen** [comment]
fixed
