### ISSUE TITLE
Get all wars a player is related to

### ISSUE THREAD

**Issue by mfnalex** [IncrediblePlugins/LandsAPI#5]
How can I get all wars that a player is related to?

I need to find out whether a player is in war with another player, but I only found LandPlayer#isInWar(War), which doesn't help me.

**Comment by Angeschossen** [comment]
added

**Comment by mfnalex** [comment]
Thanks. I'm still looking for a way to find out whether player1 is in a war against player2. Is that possible?

**Comment by Angeschossen** [comment]
war.getTeam in next v.
Or already via landPlayer.isInWar
