### ISSUE TITLE
Lands Integration Issue

### ISSUE THREAD

**Issue by TimGraham777** [IncrediblePlugins/LandsAPI#6]
PlacerholderAPI says this is a Lands Plug-in issue. Running latest release.

26.07 19:44:11 [Server] WARN Could not apply PlaceholderAPI placeholders. Disable 'AsyncPlaceholders' and try again
26.07 19:44:11 [Server] INFO java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getUniqueId()" because "<parameter1>" is null
26.07 19:44:11 [Server] INFO at me.angeschossen.lands.XzgOj.JgTVk.OWsml(?:1199) ~[?:?]
26.07 19:44:11 [Server] INFO at me.angeschossen.lands.integration.JgTVk.JgTVk.JgTVk.XzgOj(?:318) ~[?:?]
26.07 19:44:11 [Server] INFO at me.angeschossen.lands.integration.JgTVk.JgTVk.JgTVk.JgTVk(?:302) ~[?:?]
26.07 19:44:11 [Server] INFO at me.angeschossen.lands.integration.JgTVk.JgTVk.JgTVk.onPlaceholderRequest(?:285) ~[?:?]
26.07 19:44:11 [Server] INFO at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:34) ~[?:?]
26.07 19:44:11 [Server] INFO at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160) ~[?:?]
26.07 19:44:11 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70) ~[?:?]
26.07 19:44:11 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98) ~[?:?]
26.07 19:44:11 [Server] INFO at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.replacePlaceholders(ScoreboardTask.kt:107) ~[?:?]
26.07 19:44:11 [Server] INFO at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.applyPlaceholders(ScoreboardTask.kt:96) ~[?:?]
26.07 19:44:11 [Server] INFO at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run(ScoreboardTask.kt:70) ~[?:?]
26.07 19:44:11 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-83]
26.07 19:44:11 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-83]
26.07 19:44:11 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-83]
26.07 19:44:11 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
26.07 19:44:11 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
26.07 19:44:11 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?

**Comment by Angeschossen** [comment]
comes from com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.replacePlaceholders(ScoreboardTask.kt:107) ~[?:?]
the provided player is null.

**Comment by Angeschossen** [comment]
should be solved in latest
